### ISSUE TITLE
since grails 3.2.2 is out need this in grails repo as 3.2.2

### ISSUE THREAD

**Issue by lwalton-turnto** [grails-profiles/web#3]
upgrading our project to 3.2.2 (to fix another issue in 3.2.1) gave us 
"| Error Could not resolve all dependencies for configuration ':profile'. Type 'gradle dependencies' for more information"
and gradle dependencies showed:
:web: -> org.grails.profiles:web:3.2.2 FAILED

For now I have made it work by adding 
    profile 'org.grails.profiles:web:3.2.1'   
to the project.

**Comment by graemerocher** [comment]
There is no 3.2.2 release of `web`. Profiles are versioned independently from Grails

**Comment by lwalton-turnto** [comment]
Can you help me understand why a simple create-app with grails 3.2.2 which only has 
profile 'org.grails.profiles:web'
pulls 3.2.1  
but in my app if I only put 'profile 'org.grails.profiles:web'   it tries to pull 3.2.2 ?
