### ISSUE TITLE
Upgrade Bootstrap to 5.1.3

### ISSUE THREAD

**Issue by rainboyan** [grails-profiles/web#33]
Current web profile still use v4.1.3, it's time to upgrade to the new version!

There are lot CSS and JS framework now, we should support others like Foundation, Bulma, Tailwind CSS, may use profile features to implement this.

grails create-app --profile web --features bootstrap

**Comment by rainboyan** [comment]
I submit a new PR, upgrade to Bootstrap 4.6.1 first(https://github.com/grails-profiles/web/pull/37),
5.1.3 is in progress, more tests.

**Comment by rainboyan** [comment]
I created a Grails Porofile [web-bootstrap](https://github.com/rainboyan/web-bootstrap/) to integrate bootstrap easily,  update to Bootstrap v5.1.3, and support [Bootstrap Sass](https://getbootstrap.com/docs/5.0/getting-started/build-tools/#sass).
If anyone is interested, you can try it out, any feedback and discussions are welcome.

**Comment by puneetbehl** [comment]
The current version of web profile defaults to Twitter Bootstrap, we can easily bump the version to latest version of the library and do a release. One can also update the library directly in their application for now. 

Regarding the support for other libraries such as Foundation, I think extending the scaffolding plugin would be the best path forward. Also, there can be other plugins similar to scaffolding which may be use different libraries (such as scaffolding-foundation-js). I would be happy to help getting these plugin released and any other questions.

**Comment by puneetbehl** [comment]
For the work in progress, I would recommend to create a draft pull-request and refer it to this issue.
